CREATE FUNCTION setUpdatedAt()
RETURNS TRIGGER AS $$
BEGIN
	NEW.UpdatedAt = CURRENT_TIMESTAMP;
	RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE Tournament(
	TournamentId SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	Year INT NOT NULL,
	Place VARCHAR(100),
	Finished BOOLEAN,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Tournament
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

ALTER TABLE Tournament
	ADD CONSTRAINT ValidYear CHECK(Year BETWEEN 1900 AND 2050);

CREATE TABLE Representative(
	RepresentativeId SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	Surname VARCHAR(100),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Representative
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE Team(
	TeamId SERIAL PRIMARY KEY,
	RepresentativeId INT REFERENCES Representative(RepresentativeId),
	Name VARCHAR(100),
	Country VARCHAR(100),
	Contact VARCHAR(100),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Team
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE TeamAtTournament(
	TeamAtTournamentId SERIAL PRIMARY KEY,
	TournamentId INT REFERENCES Tournament(TournamentId),
	TeamId INT REFERENCES Team(TeamId),
	NumberOfPoints INT,
	FinalPosition INT, 
	PhaseReached VARCHAR(20),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE TeamAtTournament
	DROP COLUMN PhaseReached,
	ADD COLUMN PhaseReachedId INT REFERENCES GameType(GameTypeId);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON TeamAtTournament
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE GameType(
	GameTypeId SERIAL PRIMARY KEY,
	TournamentId INT REFERENCES Tournament(TournamentId),
	Name VARCHAR(100),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON GameType
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE Referee(
	Referee SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	Surname VARCHAR(100),
	DateOfBirth DATE,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Referee
	RENAME COLUMN Referee TO RefereeId

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Referee
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE Game(
	GameId SERIAL PRIMARY KEY,
	Team1Id INT REFERENCES Team(TeamId),
	Team2Id INT REFERENCES Team(TeamId),
	GameTypeId INT REFERENCES GameType(GameTypeId),
	DateAndStartTime TIMESTAMP,
	Team1Score INT DEFAULT 0,
	Team2Score INT DEFAULT 0,
	RefereeId INT REFERENCES Referee(RefereeId),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Game
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE Player(
	PlayerId SERIAL PRIMARY KEY,
	TeamId INT REFERENCES Team(TeamId),
	Name VARCHAR(100),
	Surname VARCHAR(100),
	DateOfBirth DATE,
	PlayerPosition VARCHAR(100),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON Player
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE GameEventType(
	GameEventTypeId SERIAL PRIMARY KEY,
	Name VARCHAR(100),
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON GameEventType
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();

CREATE TABLE GameEvent(
	GameEventId SERIAL PRIMARY KEY,
	GameEventTypeId INT REFERENCES GameEventType(GameEventTypeId),
	GameId INT REFERENCES Game(GameId),
	MinuteOfGame INT,
	CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE GameEvent
	ADD CONSTRAINT MaxDuration CHECK(MinuteOfGame BETWEEN 1 AND 90),
	ADD COLUMN PlayerId INT REFERENCES Player(PlayerId);

CREATE TRIGGER trgSetUpdatedAt
BEFORE UPDATE ON GameEvent
FOR EACH ROW
EXECUTE FUNCTION setUpdatedAt();